# Smart pane switching with awareness of Vim splits (Shift+hjkl)
vim_pattern='([^ ]+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n 'H' if-shell "$is_vim" 'send-keys H' 'select-pane -L'
bind-key -n 'J' if-shell "$is_vim" 'send-keys J' 'select-pane -D'
bind-key -n 'K' if-shell "$is_vim" 'send-keys K' 'select-pane -U'
bind-key -n 'L' if-shell "$is_vim" 'send-keys L' 'select-pane -R'

# Split panes
bind-key '\' split-window -h -c '#{pane_current_path}'
bind-key '-' split-window -v -c '#{pane_current_path}'

bind-key -T copy-mode-vi 'H' select-pane -L
bind-key -T copy-mode-vi 'J' select-pane -D
bind-key -T copy-mode-vi 'K' select-pane -U
bind-key -T copy-mode-vi 'L' select-pane -R
